export const animalImages: Record<string, any> = {
  raccoon: require('../../assets/images/Raccoon.png'),
  너구리: require('../../assets/images/Raccoon.png'),
  Wild_boar: require('../../assets/images/Wild_boar.png'),
  멧돼지: require('../../assets/images/Wild_boar.png'),
  Squirrel: require('../../assets/images/Squirrel.png'),
  다람쥐: require('../../assets/images/Squirrel.png'),
  Great_egret: require('../../assets/images/Great_egret.png'),
  중대백로: require('../../assets/images/Great_egret.png'),
  Hare: require('../../assets/images/Hare.png'),
  멧토끼: require('../../assets/images/Hare.png'),
  Heron: require('../../assets/images/Heron.png'),
  왜가리: require('../../assets/images/Heron.png'),
  Weasel: require('../../assets/images/Weasel.png'),
  족제비: require('../../assets/images/Weasel.png'),
  Roe_deer: require('../../assets/images/Roe_deer.png'),
  노루: require('../../assets/images/Roe_deer.png'),
  Asiatic_black_bear: require('../../assets/images/Asiatic_black_bear.png'),
  반달가슴곰: require('../../assets/images/Asiatic_black_bear.png'),
  Goat: require('../../assets/images/Goat.png'),
  고라니: require('../../assets/images/Goat.png'),
};
